apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: ginsp/ordering_app_users:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: '3003'
